systems:
  - name: MYCS8000
    resources_types: eternus_icp
    config:
      parameters:
          user: alex1
          host_keys: keys/id_rsa
          poll: 1
          use_sudo: yes
          snmp_community: public
          bastion: 172.0.0.1
      metrics:
          - name: tgt
      ips:
          - ip: 127.0.0.1
            alias: localhost
          - ip: 127.0.0.1
            ip_host_keys: keys/id_rsa
            ip_bastion: 127.0.0.1
global_parameters:
  repository: graphite
  repository_port: 2003
  repository_protocol: tcp
  loglevel: INFO
  logfile: logs/fj-collector.log