systems:
  - name: MYCS8000
    resources_types: fj_ism
    config:
      parameters:
          user: administrator
          poll: 1
          ism_password: U2FsdGVkX1+61PH0tp9qvnoG0OyhdGyFdk7LrHgj15g=
          ism_port: 25566
          ism_secure: False
      metrics:
          - name: temp
      ips:
          - ip: 172.29.1.200
            alias: localhost
global_parameters:
  repository: 10.88.0.2
  repository_port: 2003
  repository_protocol: tcp
  loglevel: DEBUG
  logfile: logs/fj-collector.log