systems:
  - name: MYCS8000
    resources_types: eternus_icp
    config:
      parameters:
          user: alex
          host_keys: keys/id_rsa
          poll: 1
          snmp_community: public
          bastion: 172.30.10.223
      metrics:
          - name: tgt
      ips:
          - ip: 172.30.10.223
            alias: localhost
          - ip: 172.30.10.223
            ip_host_keys: keys/id_rsa
            ip_bastion: 172.30.10.223
global_parameters:
  repository: graphite
  repository_port: 2003
  repository_protocol: tcp
  loglevel: DEBUG
  logfile: logs/fj-collector.log