systems:
  - name: MYCS8000
    resources_types: eternus_icp
    config:
      parameters:
          user: alex
          host_keys: keys/id_rsa
          poll: 1
          snmp_community: public
          bastion: 192.168.151.26
      metrics:
          - name: tgt
      ips:
          - ip: 192.168.151.26
            alias: localhost
          - ip: 192.168.151.26
            ip_host_keys: keys/id_rsa
            ip_bastion: 192.168.151.26
global_parameters:
  repository: 10.88.0.2
  repository_port: 2003
  repository_protocol: tcp
  loglevel: DEBUG
  logfile: logs/fj-collector.log