version: "3.9"
services:
  fj-collector:
    image: "fj-collector:latest"
    restart: unless-stopped
    volumes:
      - /opt/fj-collector/collector/logs:/collector/logs
      - /opt/fj-collector/collector/config:/collector/config
      - /opt/fj-collector/collector/keys:/collector/keys
      - /opt/fj-collector/collector/tests:/collector/tests
#    environment:
#      - ENV HTTP_PROXY="http\://10.220.3.113\:8080"
#      - ENV HTTPS_PROXY="https\://10.220.3.113\:8080"
#      - ENV FTP_PROXY="ftp\://10.220.3.113\:8080"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  graphite:
    image: "graphiteapp/graphite-statsd:latest"
    restart: unless-stopped
    ports:
    - "18125:8125/udp"
    - "12003:2003/tcp"
    - "8081:80/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/fj-collector/graphite/data/conf:/opt/graphite/conf
      - /opt/fj-collector/graphite/data/storage:/opt/graphite/storage
      - /opt/fj-collector/graphite/data/statsd_config:/opt/statsd/config
#    environment:
#      - ENV HTTP_PROXY="http\://10.220.3.113\:8080"
#      - ENV HTTPS_PROXY="https\://10.220.3.113\:8080"
#      - ENV FTP_PROXY="ftp\://10.220.3.113\:8080"
    logging:
       options:
         max-size: "10m"
         max-file: 3

  grafana:
    image: "grafana/grafana-enterprise:latest"
    restart: unless-stopped
    ports:
    - "80:3000/tcp"
    volumes:
      - /opt/fj-collector/grafana/provisioning/:/etc/grafana/provisioning/
      - /opt/fj-collector/grafana/data/grafana:/var/lib/grafana/
    user: "0"
#    environment:
#      - ENV HTTP_PROXY="http\://10.220.3.113\:8080"
#      - ENV HTTPS_PROXY="https\://10.220.3.113\:8080"
#      - ENV FTP_PROXY="ftp\://10.220.3.113\:8080"
    logging:
       options:
         max-size: "10m"
         max-file: 3

  influxdb:
    image: "influxdb:latest"
    restart: unless-stopped
    ports:
    - "8086:8086/tcp"
    volumes:
      - /opt/fj-collector/influxdb/influxdb:/var/lib/influxdb
      - /opt/fj-collector/influxdb/influxdb2:/var/lib/influxdb2
      - /opt/fj-collector/influxdb/influxdb2-config:/etc/influxdb
#    environment:
#      - ENV HTTP_PROXY="http\://10.220.3.113\:8080"
#      - ENV HTTPS_PROXY="https\://10.220.3.113\:8080"
#      - ENV FTP_PROXY="ftp\://10.220.3.113\:8080"
    logging:
       options:
         max-size: "10m"
         max-file: 3
