# Example YAML configuration file for fujitsu-collector
# A system is used to group a set of devices that compose the environment for which you want to gather performance metrics 
# For the system you define the resources that compose the system
#
# Available resource types and metrics per resource as follows:
# Servers type:
# 	primergy
#      cpu_mem  - CPU usage metrics & RAM usage metrics
#      temp     - Temperature
#      power    - Power usage
#    primequest
# Storage type:
# 	eternus_icp
#      disk     - Filesystem/Storage usage metrics
#    eternus-dx
#    eternus-lt
#    netapp-fas
# Switch type:
#	 san-switch-brocade
#	 lan-switch-cisco
# Operating System type:
# 	linux_os
#      cpu_mem  - CPU usage metrics & RAM usage metrics
#   win-os
#   esxi-os
# RESTFull API type:
#	 vmware-vcenter 
#
---
systems:
  - name: MYCS8000    
    config:
      - resources_types: eternus_icp
        parameters:
          user: dx_usr
          host_keys: /collector/fj-collector/config/id_rsa
          known_hosts: /collector/fj-collector/config/known_hosts
          poll: 0
        metrics:
          - name: fs
        ips:
          - ip: 192.168.0.221
            alias: DX600
          - ip: 192.168.0.221
            alias: DX200

global parameters:
  repository: graphite
  repository_port: 2003
  repository_protocol: tcp
  log: INFO # NOTSET, DEBUG, INFO, WARN, ERROR, CRITICAL
  logfile: logs/fj-collector.log