systems:
  - name: MTST2
    resources_types: eternus_icp
    config:
      parameters:
          user: alex
          host_keys: keys/id_rsa
          poll: 1
      metrics:
          - name: fs
      ips:
          - ip: 127.0.0.1
            alias: localhost
          - ip: 127.0.0.1
            alias: new-localhost
            ip_host_keys: keys/id_rsa
            ip_bastion: 127.0.0.1
global_parameters:
  repository: influxdb
  repository_port: 8086
  repository_protocol: tcp
  repository_api_key: hhhhhhh
  loglevel: DEBUG
  logfile: logs/fj-collector.log
  auto_fungraph: yes
  grafana_api_key: hhhhh
  grafana_server: grafana