systems:
  - name: dev_env_99
    resources_types: eternus_cs8000
    config:
      parameters:
        user: super
        host_keys: keys/id_rsa
        poll: 1
      metrics:
        - name: fs_io
        - name: fs
        - name: cpu
        - name: mem
      ips:
        - ip: 127.0.0.1
          alias: linux14
        - ip: 127.0.0.1
  - name: dev_env_99
    resources_types: eternus_cs8000
    config:
      parameters:
        user: super
        host_keys: keys/id_rsa
        poll: 1
      metrics:
        - name: fs
      ips:
        - ip: 127.0.0.1
          alias: linux25
  - name: dev_env_99
    resources_types: eternus_cs8000
    config:
      parameters:
        user: super
        host_keys: keys/id_rsa
        poll: 1
      metrics:
        - name: net
      ips:
        - ip: 127.0.0.1
          alias: linux14
  - name: dev_env_99
    resources_types: linux_os
    config:
      parameters:
        user: super
        host_keys: keys/id_rsa
        poll: 1
      metrics:
        - name: cpu
      ips:
        - ip: 127.0.0.1
          alias: linux22
global_parameters:
  repository: influxdb
  repository_port: 8086
  repository_protocol: tcp
  repository_api_key: TOBEDEFINED
  loglevel: DEBUG
  logfile: logs/fj-collector.log
  auto_fungraph: yes
  grafana_api_key: TOBEDEFINED
  grafana_server:  localhost