systems:
  - name: dev_env_99
    resources_types: eternus_cs8000
    config:
      parameters:
        user: fjcollector
        host_keys: keys/id_rsa
        poll: 1
      metrics:
        - name: fs_io
        - name: fs
        - name: cpu
        - name: mem
        - name: medias
        - name: fc
      ips:
        - ip:  172.17.36.184
          alias: linux14
        - ip:  172.17.36.184
          alias: linux02
global_parameters:
  repository: influxdb
  repository_port: 8086
  repository_protocol: tcp
  repository_api_key: TOBEDEFINED
  loglevel: ERROR
  logfile: logs/fjcollector.log
  auto_fungraph: yes
  grafana_api_key: TOBEDEFINED
  grafana_server: grafana
