systems:
  - name: MTST2
    resources_types: eternus_icp
    config:
      parameters:
          user: alex
          host_keys: keys/id_rsa
          poll: 1
      metrics:
          - name: fs
      ips:
          - ip: 127.0.0.1
            alias: localhost
          - ip: 127.0.0.1
            alias: new-localhost
            ip_host_keys: keys/id_rsa
            ip_bastion: 127.0.0.1
global_parameters:
  repository: graphite
  repository_port: 2003
  repository_protocol: tcp
  repository_org: fj-collector
  collector_root: ETERNUS
  loglevel: DEBUG
  logfile: logs/fj-collector.log
  grafana_auto_fun: yes
  grafana_api_key: glsa_kZXQZaFS8dY2F7jPTF1kjuxmdOAAgpdD_6051d174
  influxdb_api_key: hhhhhhh
  grafana_server: grafana