systems:
  - name: dev_env_99
    resources_types: eternus_icp
    config:
      parameters:
        user: super
        host_keys: keys/id_rsa
        poll: 1
      metrics:
        - name: fs_io
        - name: fs
        - name: cpu
        - name: mem
      ips:
        - ip: 127.0.0.1
          alias: linux14
        - ip: 127.0.0.1
  - name: dev_env_99
    resources_types: eternus_icp
    config:
      parameters:
        user: super
        host_keys: keys/id_rsa
        poll: 1
      metrics:
        - name: fs
      ips:
        - ip: 127.0.0.1
          alias: linux25
  - name: dev_env_99
    resources_types: linux_os
    config:
      parameters:
        user: super
        host_keys: keys/id_rsa
        poll: 1
      metrics:
        - name: net
      ips:
        - ip: 127.0.0.1
          alias: linux14
  - name: dev_env_99
    resources_types: linux_os
    config:
      parameters:
        user: super
        host_keys: keys/id_rsa
        poll: 1
      metrics:
        - name: cpu
      ips:
        - ip: 127.0.0.1
          alias: linux22
global_parameters:
  repository: influxdb
  repository_port: 8086
  repository_protocol: tcp
  repository_api_key: 11pOy9Qzp_zdiljjrXTnvYXMV4cxUOr_pQB-6VFlzbU1LMe51hSWZi2X3MpBla5bR5rzo6_hxJh6BPOoDt67AA==
  loglevel: DEBUG
  logfile: logs/fj-collector.log
  auto_fungraph: yes
  grafana_api_key: glsa_7AjCeAulfV62Ekj7Z85Ck5Z1xA8cBvNA_78139d28
  grafana_server:  localhost