systems:
  - name: MTST2
    resources_types: eternus_icp
    config:
      parameters:
          user: alex
          host_keys: keys/id_rsa
          poll: 1
      metrics:
          - name: fs
      ips:
          - ip: 172.22.58.55
            alias: localhost
          - ip: 172.22.58.55
            alias: new-localhost
            ip_host_keys: keys/id_rsa
            ip_bastion: 172.22.58.55
global_parameters:
  repository: gaphite
  repository_port: 2003
  repository_protocol: tcp
  collector_root: eternus_new2
  loglevel: DEBUG
  logfile: logs/fj-collector.log
  grafana_auto_fun: no
  grafana_api_key: glsa_kZXQZaFS8dY2F7jPTF1kjuxmdOAAgpdD_6051d174
  grafana_server: grafana:8080
